[book]
title = "Borger Documentation"
authors = ["luisfonsivevo"]
language = "en"

[output.html]
default-theme = "rust"
site-url = "/docs/"
theme = "theme"
additional-js = ["llms.js"]

[output.html.playground]
runnable = false

[output.llms-txt-full]

[preprocessor.gitinfo]
header = true
footer = false
date-format = "%-m/%-d/%Y"
time-format = ""
branch = "master"
align.header = "right"
message.header = "<em>Edited {{date}}</em>"
