[book]
title = "Borger Documentation"
authors = ["luisfonsivevo"]
language = "en"

[output.html]
default-theme = "rust"
site-url = "/docs/"
theme = "theme"
additional-js = ["llms.js"]

[output.llms-txt-full]
