name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug git state
        run: |
          git log -1 --format="%ci" -- src/README.md
          git branch
          git status

      - name: Build book
        run: mdbook build
        env:
          PATH: ${{ github.workspace }}/.github/workflows:$PATH

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Clone borger template
        run: git clone --depth=1 --recurse-submodules --shallow-submodules https://github.com/BorgerLand/BlankTemplate.git /tmp/borger

      - name: Build cargo doc
        run: |
          cd /tmp/borger
          bun install --frozen-lockfile
          cd borger/code_generator
          bun src/main.ts
          cd ../engine
          cargo doc --no-deps

      - name: Assemble site
        run: |
          mkdir -p _site/docs
          cp -r book/html/. _site/docs
          cp -r /tmp/borger/target/doc _site/docs/api/rust
          cp -r readme book/llms-txt-full/llms-full.txt index.html _site
          cp book/llms-txt-full/llms-full.txt _site/llms.txt
          mv _site/docs/404.html _site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
